### ISSUE TITLE
Multiple URLs often double post to the same URL, rather than sending to both

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#589]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

We have a few users with multiple URLs, we have a bug where they will sometimes send an event to endpoint # 001 and endpoint # 002 correctly, then about 75% of the time Dink will either send 2 events to endpoint # 001 or endpoint # 002, resulting in double posting, or not posting at all.

We are unable to find specific logic, it seems genuinely quite random, but extremely consistent.

Below are some logs of the webservice receiving a double post, notably to the same endpoint (rather than 1x notification to each in their config), and note the killCount are the same, indicating this is the same event twice.

We have many more examples of this if required

```
0|KB2  | 09/11 18:29: New API event: {
0|KB2  | 09/11 18:29:   route_url: '{end point 001 omitted for security}',
0|KB2  | 09/11 18:29:   event_type: 'LOOT',
0|KB2  | 09/11 18:29:   has_file: false,
0|KB2  | 09/11 18:29:   player_name: 'hulkerton',
0|KB2  | 09/11 18:29:   account_type: 'GROUP_IRONMAN',
0|KB2  | 09/11 18:29:   dink_hash: '53f05567d4105609f46bcb326e9a87a1a78b91dfd92cd976327f27b9',
0|KB2  | 09/11 18:29:   extra: {
0|KB2  | 09/11 18:29:     items: [ [Object], [Object] ],
0|KB2  | 09/11 18:29:     source: 'Outlaw',
0|KB2  | 09/11 18:29:     category: 'NPC',
0|KB2  | 09/11 18:29:     killCount: 6,
0|KB2  | 09/11 18:29:     rarestProbability: 0.04688232536333802,
0|KB2  | 09/11 18:29:     npcId: 4169
0|KB2  | 09/11 18:29:   },
0|KB2  | 09/11 18:29:   account_dbo: RowDataPacket {
0|KB2  | 09/11 18:29:     account_uuid: 'f23ec828-3f29-4df3-bc71-e8c4f306bf21',
0|KB2  | 09/11 18:29:     dink_hash: '53f05567d4105609f46bcb326e9a87a1a78b91dfd92cd976327f27b9',
0|KB2  | 09/11 18:29:     account_name: 'hulkerton',
0|KB2  | 09/11 18:29:     account_gamemode: 'GROUP_IRONMAN',
0|KB2  | 09/11 18:29:     api_id: '{omitted}',
0|KB2  | 09/11 18:29:     discord_user_id: '{omitted}',
0|KB2  | 09/11 18:29:     created_at: 1728228222472,
0|KB2  | 09/11 18:29:     updated_at: 1730794187485,
0|KB2  | 09/11 18:29:     group_uuid: '45731632-103f-46aa-af04-05dee6cf5484',
0|KB2  | 09/11 18:29:     group_name: 'YGO Boys',
0|KB2  | 09/11 18:29:     group_gamemode: 'GROUP_IRONMAN'
0|KB2  | 09/11 18:29:   }
0|KB2  | 09/11 18:29: }
0|KB2  | 09/11 18:29: New API event: {
0|KB2  | 09/11 18:29:   route_url: '{end point 001 omitted for security}',
0|KB2  | 09/11 18:29:   event_type: 'LOOT',
0|KB2  | 09/11 18:29:   has_file: false,
0|KB2  | 09/11 18:29:   player_name: 'hulkerton',
0|KB2  | 09/11 18:29:   account_type: 'GROUP_IRONMAN',
0|KB2  | 09/11 18:29:   dink_hash: '53f05567d4105609f46bcb326e9a87a1a78b91dfd92cd976327f27b9',
0|KB2  | 09/11 18:29:   extra: {
0|KB2  | 09/11 18:29:     items: [ [Object], [Object] ],
0|KB2  | 09/11 18:29:     source: 'Outlaw',
0|KB2  | 09/11 18:29:     category: 'NPC',
0|KB2  | 09/11 18:29:     killCount: 6,
0|KB2  | 09/11 18:29:     rarestProbability: 0.04688232536333802,
0|KB2  | 09/11 18:29:     npcId: 4169
0|KB2  | 09/11 18:29:   },
0|KB2  | 09/11 18:29:   account_dbo: RowDataPacket {
0|KB2  | 09/11 18:29:     account_uuid: 'f23ec828-3f29-4df3-bc71-e8c4f306bf21',
0|KB2  | 09/11 18:29:     dink_hash: '53f05567d4105609f46bcb326e9a87a1a78b91dfd92cd976327f27b9',
0|KB2  | 09/11 18:29:     account_name: 'hulkerton',
0|KB2  | 09/11 18:29:     account_gamemode: 'GROUP_IRONMAN',
0|KB2  | 09/11 18:29:     api_id: '{omitted}',
0|KB2  | 09/11 18:29:     discord_user_id: '{omitted}',
0|KB2  | 09/11 18:29:     created_at: 1728228222472,
0|KB2  | 09/11 18:29:     updated_at: 1730794187485,
0|KB2  | 09/11 18:29:     group_uuid: '45731632-103f-46aa-af04-05dee6cf5484',
0|KB2  | 09/11 18:29:     group_name: 'YGO Boys',
0|KB2  | 09/11 18:29:     group_gamemode: 'GROUP_IRONMAN'
0|KB2  | 09/11 18:29:   }
0|KB2  | 09/11 18:29: }
```

### Screenshots

![image](https://github.com/user-attachments/assets/182b7be5-7f6b-4cc7-bd6a-bc77841835f1)

### Runelite Logs

[client.log](https://github.com/user-attachments/files/17686165/client.log)

### Runelite Version

1.10.43 - Rev 226 - 2.7.1

**Comment by APKiwi** [comment]
Additional info is the endpoints are both present in "Primary Webhook URLs", separated via a new line char (no other space/char) and there are no values (double checked/reset config) in all "Webhook Overrides" fields.

**Comment by iProdigy** [comment]
how many seconds were between the two posts & what is the value of `Webhook Retry Base Delay` in their settings?

**Comment by APKiwi** [comment]
Almost instant posting, sub 1-2 seconds, the `Webhook Retry Base Delay` is set to 2000ms, `Image Upload Timeout` 30s.

**Comment by iProdigy** [comment]
hm, somehow is related to retries since dink is logging 503's sometimes when posting to your endpoint
```
2024-11-05 18:09:09 AEST [OkHttp https://{omitted}/...] WARN  d.message.DiscordMessageHandler - There was an error sending the webhook message
java.lang.RuntimeException: Received unsuccessful http response: 503 -  - <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ddb5bd82f31e7c0',t:'MTczMDc5NDEzOS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>


	at dinkplugin.message.DiscordMessageHandler$1.onResponse(DiscordMessageHandler.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-11-05 18:09:09 AEST [OkHttp https://{omitted}/...] WARN  d.message.DiscordMessageHandler - There was an error sending the webhook message
java.lang.RuntimeException: Received unsuccessful http response: 503 -  - <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ddb5bd82f2ee7c0',t:'MTczMDc5NDEzOS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>


	at dinkplugin.message.DiscordMessageHandler$1.onResponse(DiscordMessageHandler.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-11-05 18:09:48 AEST [OkHttp https://{omitted}/...] WARN  d.message.DiscordMessageHandler - There was an error sending the webhook message
java.lang.RuntimeException: Received unsuccessful http response: 503 -  - <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ddb5ccbdf1de7c0',t:'MTczMDc5NDE3OC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>


	at dinkplugin.message.DiscordMessageHandler$1.onResponse(DiscordMessageHandler.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-11-05 18:09:48 AEST [OkHttp https://{omitted}/...] WARN  d.message.DiscordMessageHandler - There was an error sending the webhook message
java.lang.RuntimeException: Received unsuccessful http response: 503 -  - <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ddb5ccbdf1ce7c0',t:'MTczMDc5NDE3OC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>


	at dinkplugin.message.DiscordMessageHandler$1.onResponse(DiscordMessageHandler.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by APKiwi** [comment]
I did see those too as I was combing the logs - those appear to be genuine service interruptions between my users client and the host, they are at different time stamps and the frequency of the double post (at the high verbosity we use we receive each kill and each loot event) we see this happening 20+ times a minute

**Comment by iProdigy** [comment]
when your service 503's, does the `Retry-After` header happen to be set to 0?

**Comment by APKiwi** [comment]
Had check my haproxy config, but yes `Retry-After` is `0` on 503. However, I don't believe these are related to 503s, as we don't have many of them on record and this issue is consistently reproduce-able without getting any 503s

**Comment by iProdigy** [comment]
I'm unable to replicate this issue - is your custom handler on github? (if it's a private repo could you add my account to take a look)

**Comment by APKiwi** [comment]
The problem could definitely be on my side :P happy if you take a look. The handler is webhooks/api_game_osrs.js

**Comment by iProdigy** [comment]
thanks - your handler is a bit more complex than I anticipated so can't thoroughly look through it

that said: for your `channel.send` call within `send_embed`, could you wrap the body of the `then` callback within a try/catch (might not be the problem, but don't have the time to look through discord.js to confirm)

**Comment by APKiwi** [comment]
No problem, it is indeed very meaty.

I don't see that being the problem, the embed is being sent after all just receiving the wrong endpoint to submit to. I should clarify too; the two endpoints used are both processed by my endpoint/handler, they just end up in different discords. 

Essentially each user has a unique URL (like domain/endpoint/guild_id/user_id/GUID) per discord they are in (that also has the bot + they wish to post their accounts to). We have multiple users in multiple discords who only want to post in specific ones despite the bot being in most of them, so we are in this situation where they have a unique URL per guild per user.

That said, I have added the try/catch where specified and will re-test if there are any additional logs when this occurs

**Comment by APKiwi** [comment]
We just re-tested, double posting occurred with no additional log/error (from the `catch{}`)

**Comment by Felanbird** [comment]
fwiw I'm like 500 notifs into testing (1 loot 1 kc from each boss kill) without any dupes

**Comment by APKiwi** [comment]
That is definitely significant, just confirming you have two seperate URLs being used?

I don't really know where else to check (I had done significant debugging before raising this issue) as the server is reporting 2x notifications to the same end point.

I'll see if I can add some even earlier logging to the handler but I suspect I will get the same result hitting it.

I also have cloudflare between, but I don't think that has an impact (it shouldn't).

**Comment by APKiwi** [comment]
I found the problem. Global variable being overwritten on close consecutive calls from a time before we had multiple URLs, my bad. Thanks both for looking into it
